---
- name: Config Web VM with Docker
  hosts: webservers
  become: true
  tasks:
    - name: Install docker.io using apt module
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: Install python3-pip using apt module
      apt:
        name: python3-pip
        state: present

    - name: Install Docker python using pip module
      pip:
        name: docker
        state: present

    - name: Download and Launch a docker web container dvwa and publish on port 80
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        restart_policy: always
        published_ports: 80:80

    - name: Enable docker service on boot
      systemd:
        name: docker
        enabled: yes
