---
- name : Configure Elk VM with Docker
  hosts: elk
  become: true
  tasks:
     - name: Install docker.io using apt module
       apt:
           update_cache: yes
           force_apt_get: yes
           name: docker.io
           state: present

     - name: Install python3-pip using apt module
       apt:
           force_apt_get: yes
           name: python3-pip
           state: present

     - name: Install python docker module using pip module
       pip:
           name: docker
           state: present

     - name: Increase virtual memory using sysctl module
       command: sysctl -w vm.max_map_count=262144

     - name: Increase virtual memory on restart
       shell: echo "vm.max_map_count=262144" >> /etc/sysctl.conf

     - name: Download and Launch Docker ELK container
       docker_container:
           name: elk
           image: sebp/elk:761
           state: started
           restart_policy: always
           published_ports:
               - 5601:5601
               - 9200:9200
               - 5044:5044

     - name: Enable service docker on boot
       systemd:
            name: docker
            enabled: yes